const os = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIp() {
    const interfaces = os.networkInterfaces();
    for (const name of Object.keys(interfaces)) {
        for (const iface of interfaces[name]) {
            // Skip internal (loopback) and non-IPv4 addresses
            if (iface.family === 'IPv4' && !iface.internal) {
                return iface.address;
            }
        }
    }
    return '127.0.0.1';
}

const currentIp = getLocalIp();
const configPath = path.join(__dirname, '..', 'src', 'config', 'env.js');
const configDir = path.dirname(configPath);

// Create config directory if it doesn't exist
if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
}

const content = `// This file is auto-generated by mobile/scripts/update-ip.js
// DO NOT EDIT MANUALLY.
export const BASE_URL = 'http://${currentIp}:5000/api';
`;

fs.writeFileSync(configPath, content);
console.log(`🚀 Updated mobile API URL to: http://${currentIp}:5000/api`);
