// This file is auto-generated by mobile/scripts/update-ip.js
// For cloud deployment, this points to the permanent Render URL.
// DO NOT EDIT MANUALLY.
export const BASE_URL = 'https://smartcrew-api.onrender.com/api';
